[package]
name = "threadsafe_zmq_example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
threadsafe_zmq = { path = "../src", version = "1.0.0" }