on: [push, pull_request]

name: CI

jobs:
  setup:
    name: Setup and Check Toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Display Rust version
        run: rustc --version

  check:
    name: Check Workspace
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run cargo check for all workspace members
        run: cargo check --workspace --all-targets

  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run tests for all workspace members
        run: cargo test --workspace --all-targets

  lints:
    name: Run Lints
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings